remote_theme: pmarsceill/just-the-docs
title: "phly/keep-a-changelog"
description: "CLI tooling for Keep-A-Changelog-formatted CHANGELOG.md files, written in PHP"
show_downloads: false
color_scheme: "dark"
aux_links:
  "GitHub":
    - "//github.com/phly/keep-a-changelog"
